



```{r initialize, echo=FALSE,results='hide',message=FALSE,warning=FALSE}
# Initialize!

# Stop R from interpreting strings as factors. 
# When you want factors, you'll know it.
options(stringsAsFactors = FALSE)

# Load up the requisite packages
library(knitr)     # It's a knitr document, after all...
library(to1check)  # All TO1-related functions
library(plyr)      # For the count() and arrange() functions
library(xtable)    # For printing data.frames nicely
library(lubridate) # For calculating number of weeks remaining

# Set default chunk options
opts_chunk$set(echo = FALSE,
               results = 'asis',
               message = FALSE,
               warning = FALSE,
               error = TRUE)


# Load the local info (edit this if your results are wrong)
local_facts <- read.csv("local_facts.csv")

# Load the latest cleaned data
load(local_facts$datapath)

# Set aside those who were successfully enrolled during the 
# in question - we'll generally disregard those who declined 
# or who didn't complete enrollment 

enrolled <- with(to1clean$master,
    StudyId[!CloseReason %in% c("Didn't complete enrollment", "Withdrew") &
            VisitDate >= as.Date(local_facts$period_start) &
            VisitDate <= as.Date(local_facts$period_end)]
)


# Set up subsets of just the participants enrolled this period
enrolled_master <- to1clean$master[to1clean$master$StudyId %in% enrolled, ]



# Set up default print arguments for printing tables:
# xtable() makes data.frames more suitable for display
# format() converts all of the data.frame comments to character*;
# print() writes the xtable object to HTML

# *print() for xtable throws a tantrum over Date and POSIXct variables,
# so they have to be converted to character before printing 

dfprint <- function(df, printdigits = 2) {
    print(
        xtable(format(df, 
                      na.encode = FALSE, 
                      digits = printdigits, 
                      nsmall = printdigits), 
               align = c("l", "l", rep("c", ncol(df) - 1))
        ),
        type = "html",
        include.rownames = FALSE,
        NA.string = "-")
}




```

<h1 class='maintitle'>TBESC TO 1 Results Summary: `r local_facts$site`</h1>
<h3 class='maintitle'>Enrollment Period: `r paste(local_facts$period_start, "through", local_facts$period_end)`</h3>
<span class='maintitle'>Report generated at `r format(Sys.time())`</span>


```{r}

# Total enrolled so far (I need a better measure of this)
total_enrolled <- length(enrolled)

```

Total Enrolled to Date: `r total_enrolled`




### Participants by Country of Origin
```{r,results="hide",fig.width = 8, fig.height = 8}

# Tally up participants by their country of birth
birthco <- arrange(count(enrolled_master, var = "BirthCountry"), 
                   freq, BirthCountry)

# BirthCountry = "" or NA indicates a pre-enrolled person
birthco$BirthCountry[birthco$BirthCountry %in% c("", NA)] <- "Pre-enrolled"

# Make BirthCountry a factor - this ensures descending order of the bars
birthco$BirthCountry <- factor(birthco$BirthCountry,  
                               levels = birthco$BirthCountry)



# Plot it
ggplot(birthco, aes(x = BirthCountry, weight = freq)) +
  geom_histogram() +
  coord_flip() +
  labs(title = "Enrollment by country of birth",
       x = "Country of Birth",
       y = "Number Enrolled")

```


```{r}
### Participant Ages
```


### Test Results

```{r,results='hide'}
##################################################
# Summarize participants' individual test results
testres <- compile_results(to1clean)

testres_enrolled <- testres[testres$StudyId %in% enrolled, ]


# Cast all results into a wide table - keep only the results of
# participants enrolled in this period
testwide <- dcast(
                melt(testres_enrolled,
                     id.var = "StudyId", 
                     measure.var = c("tst", "qft", "tspot")),
                variable ~ value,
                fun.agg = length
)

# Tidy up for printing
# Prettier test names
testwide$variable <- toupper(as.character(testwide$variable))

# Better column order
testwide <- testwide[ , c("variable", "Negative", "Positive", 
                          "Borderline", "NA")]


# Pretty names
names(testwide)[names(testwide) %in% "variable"] <- "Test"


##################################################
# Individual test results - proportions
testwide.prop <- dcast(
                     melt(testres_enrolled,
                          id.var = "StudyId", 
                          measure.var = c("tst", "qft", "tspot")),
                     variable ~ value,
                     fun.agg = function(x) { length(x) / nrow(testres_enrolled) * 100}
)

# Tidy up for printing
# Prettier test names
testwide.prop$variable <- toupper(as.character(testwide.prop$variable))

# Better column order
testwide.prop <- testwide.prop[ , c("variable", "Negative", "Positive", 
                                    "Borderline", "NA")]


# Pretty names
names(testwide.prop)[names(testwide.prop) %in% "variable"] <- "Test"



##################################################
# Aggregate by result class
testagg <- count(testres_enrolled, var = c("result_class"))

# Make a factor of result_class by descending frequency for plotting later on
testres_enrolled$plot_class <- factor(testres_enrolled$result_class,
                                      levels = arrange(testagg, freq)$result_class)



##################################################
# Make a factor of result_class for the table - this is more a logical ordering:
# Triple-neg, triple-pos, isolated-pos, isolated-neg
testagg$result_class <- factor(testagg$result_class,
                               levels = c("Triple Negative", "Triple Positive",
                                          "Isolated TST+", "Isolated QFT+", 
                                          "Isolated TSPOT+",
                                          "Isolated TST-", "Isolated QFT-", 
                                          "Isolated TSPOT-",
                                          "Inconclusive")
)
```


Count:

```{r}

# Number positive on each test
dfprint(testwide)

```

Proportion:

```{r}
# Proportion positive on each test
dfprint(testwide.prop)

```




```{r, results="hide",fig.width = 8, fig.height = 8}


ggplot(testres_enrolled, aes(x = plot_class)) +
  geom_bar() +
  coord_flip() +
  labs(x = "Number of Participants", y = "Result")

```


```{r}

# Add a proportion-of-enrolled indicator
testagg$classprop <- round(testagg$freq / nrow(testres_enrolled) * 100, 2)

# Pretty names
names(testagg) <- c("Results", "Freq", "Proportion")


dfprint(arrange(testagg, Results))

```


```{r}
### Test Results by Country of Origin
```


```{r}
### Test Results by Risk Factor
```


```{r}
### Treatment Acceptance
```





